### ISSUE TITLE
There are many options including the one in this fork: https://github.com/bombardier-gif/covid-vaccine-booking

### ISSUE THREAD

**Issue by sandystays** [pallupz/covid-vaccine-booking#105]
I did try the bombardier method of automatically reading the SMS but IFFT app (paid subscription) on mobile but it is NOT able to transmit the SMS to JSON. IFFT app gives the following error "Rate limited by the remote server https://json.extendsclass.com/bin/xxxxxxxxxx"

**Comment by pallupz** [comment]
wrong repo
