### ISSUE TITLE
Closing screen

### ISSUE THREAD

**Issue by satamyaduka** [pallupz/covid-vaccine-booking#109]
Your Script works like magic really. I have been trying to book a slot for 2 days manually. But It never gets booked.

But your script booked it in less than 5 secs. 

**But as soon as we confirm slot booking by pressing a button, the application closed itself. 
I think a confirmation page or asking to exit will be great, as a person can appreciate what the great thing it is.**

**Comment by pallupz** [comment]
Good suggestion. I will try to add it in the next commit.

**Comment by sixfooter** [comment]
>But as soon as we confirm slot booking by pressing a button, the application closed itself.

@pallupz  i noticed this behavior too yest. with the yesterday's 3PMversion 
It asked me to confirm the slot for some reason , though i had selected the option of "yes-please" of auto confirmation.

**Comment by pallupz** [comment]
that is weird. would you have screenshots or logs to help debug that behavior?

**Comment by sixfooter** [comment]
>that is weird. would you have screenshots or logs to help debug that behavior?

I couldn't take as the control jumped to the first stage asking me to regenerate the OTP and when i hit enter the exe.'s window got closed. How to

**Comment by pallupz** [comment]
I haven't created a separate closing screen but, now you'll have to press any key thrice to exit. I know, not the best solution but time to develop is a problem. Went with a simple hack approach here.
