### ISSUE TITLE
Unable to cancel my slot (same day). Is there an API to delete my beneficiary instead?

### ISSUE THREAD

**Issue by ravikiran2809** [pallupz/covid-vaccine-booking#112]
So i booked a Covaxin slot through the script (using auto-book) for today. Its not letting me cancel appointment for the same day however. Is there a way to delete my beneficiary so I can re-add later?

**Comment by pallupz** [comment]
Only cancel option I have used is on the portal. I haven't had to use that for same day slots. There are [cancelAppointment](https://apisetu.gov.in/public/marketplace/api/cowin/cowinapi-v2#/Vaccination%20Appointment%20APIs/cancelAppointment) and reschedule APIs. You can give that a try.
