### ISSUE TITLE
Are we getting OTP through when executing SCRIPT

### ISSUE THREAD

**Issue by sharpant-dot** [pallupz/covid-vaccine-booking#113]
i am not getting otp when running script.. i am able to get the same through the cowin site, any similar behaviour?

**Comment by sharpant-dot** [comment]
or are the numbers getting blacklisted?

**Comment by manasshukla1** [comment]
No, I get OTP each time while running this script. Why don't you try some other number?

**Comment by pallupz** [comment]
The OTP does get delayed sometimes. If you see the 'Enter OTP: ' input, that means OTP request was posted successfully. 
If it doesn't arrive, try after 5-10 mins
