### ISSUE TITLE
Filter out centers with availability less than ? Minimum 1 :

### ISSUE THREAD

**Issue by samnahdi** [pallupz/covid-vaccine-booking#114]
What does this actually mean - "Filter out centers with availability less than ? Minimum 1 :"
If I select '1', it will only pull centers that have atleast 1 open slot....shouldn't it be maximum instead ?

**Comment by sharpant-dot** [comment]
no, it will be min... if 2 ppl are booking , then they might want same center. in that case it wont pick slots where only 1 is open.
