### ISSUE TITLE
automatically book the next slot in auto booking mode 

### ISSUE THREAD

**Issue by sharpant-dot** [pallupz/covid-vaccine-booking#115]
Here we have to press any key to continue, instead if the booking failed it should just keep automatically trying other slots without user input

+-------+-------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name              | district   |   pincode |   available | date       | slots                                                                        |
+=======+===================+============+===========+=============+============+==
============================================================================+
|     1 | APOLLO HOSPITAL 1 | BBMP       |    560076 |           1 | 07-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-04:00PM'] |
+-------+-------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
AUTO-BOOKING IS ENABLED. PROCEEDING WITH FIRST CENTRE, DATE, and RANDOM SLOT.
============> Got Choice: Center #1, Slot #3
Booking with info: {'beneficiaries': ['xxxxxxxxxxxxxxxx'], 'dose': 1, 'center_id': 566035, 'session_id': '0ee65cd7-39de-463a-b86b-6e25c62f1a8e', 'slot': '01:00PM-03:00PM'}
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Press any key to continue . . .

**Comment by pallupz** [comment]
The script doesn't exit though, right? It goes back and shows the next set of options?

**Comment by arca000** [comment]
It doesn't exit, but needs a key input to proceed to the next.

**Comment by sharpant-dot** [comment]
you have to press enter.. and if u r not near the system you will loose out..

**Comment by pallupz** [comment]
okay.. will remove that system pause

**Comment by pallupz** [comment]
This has been implemented in the latest version
