### ISSUE TITLE
Paid and Free

### ISSUE THREAD

**Issue by arca000** [pallupz/covid-vaccine-booking#117]
This is not an issue but Government centers aren't administering shots for 18-45. But they keep enabling slots - only to be turned away.
Possible to add a tag - Paid or free? Paid ones usually honour the appointment.
This isn't the same as PINCODE search people are still open to travel anywhere in the city as long as it is a confirmed shot.

Please consider.
![WhatsApp Image 2021-05-03 at 10 06 51 AM](https://user-images.githubusercontent.com/65480461/117403132-52a30c00-af25-11eb-87c9-7845dcf1158b.jpeg)

**Comment by pallupz** [comment]
I can try to add Paid/Free filtering

**Comment by arca000** [comment]
That will be helpful. Thank you.

**Comment by pallupz** [comment]
This has been implemented in the latest version
