### ISSUE TITLE
Vaccine name included in beneficiary even on cancellation - influences vaccine preference input

### ISSUE THREAD

**Issue by vinayd2** [pallupz/covid-vaccine-booking#118]
A condition arises where "preferred vaccine choice" is not offered anymore. When a appointment was cancelled (in this case it was auto cancelled by the system - appears to be some internal error), the beneficiary details list the vaccine name even though status indicates "Not Vaccinated". (snipped below) 
This leads to a condition where the program does not offer the choice of vaccination anymore and the vaccine (COVISHIELD in below snip) is chosen by default.

Simple workaround was to save as json and edit out the vaccine and preference details from the json and rerun.

An enhancement could be considered in automatically choosing the vaccine only if status is "Partially Vaccinated"

beneficiary_dtls	:
+-------+----------------+---------------------------------+-----------+-------+----------------+
|   idx |        bref_id | name                            | vaccine   |   age | status         |
+=======+================+=================================+===========+=======+================+
|     1 |  xxxxxxx  | John    |    COVISHIELD       |    nn  | Not Vaccinated |
+-------+----------------+---------------------------------+-----------+-------+----------------+
|     2 | xxxxxxx  | Snow .. |   COVISHIELD       |    nn | Not Vaccinated |
+-------+----------------+---------------------------------+-----------+-------+----------------+

**Comment by pallupz** [comment]
When you edited the json file, where you able to book a slot for the other vaccine?

As in, if the vaccine tagged against a 'Not Vaccinated' person does not match with the vaccine we are trying to book the appointment for, does it succeed?

**Comment by vinayd2** [comment]
Unfortunately I have not been successful in booking - so unable to confirm.

**Comment by pallupz** [comment]
Ohk. It would be risky to implement this unless we know that it will succeed.

It's a simple change. For testing, would you be willing to try booking for a future date in a city with high availability - like say Delhi? You can then cancel the appointment from the portal. Or I will wait for some news from your end depending on your success.

**Comment by vinayd2** [comment]
The beneficiary list indicates COVISHIELD, so ill be on the lookout for COVAXIN availability for this test and let you know.

**Comment by samdsai** [comment]
Sorry, I am not good on script level but can some share the scripts , and share me the step to run it that will be really helpful.

**Comment by pallupz** [comment]
Doesn't matter. They implemented captcha. So it's game over - at least for now

**Comment by axd123** [comment]
@pallupz have they already?

**Comment by pallupz** [comment]
@axd123 I have implemented option to enter Captcha. No more auto-booking.
