### ISSUE TITLE
Captcha implemented?

### ISSUE THREAD

**Issue by mrms123** [pallupz/covid-vaccine-booking#123]
Getting the below response - did they implement a CAPTCHA?

```
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}
Response: 400 : {"errorCode":"APPOIN0044", "error":"Please enter valid security code"}

```

**Comment by nirlendu** [comment]
@pallupz  the slot booking requests are protected - https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2
I think every API will work as expected apart from appointment schedule/reschedule/cancel

**Comment by mrms123** [comment]
@nirlendu - Booking was working earlier - they implemented a captcha today

Captcha is now visible on the website as well. 
![image](https://user-images.githubusercontent.com/28861042/117423550-77f04400-af3e-11eb-952f-b38fc195aee5.png)

**Comment by pallupz** [comment]
Yup - party is officially over! :(

**Comment by pallupz** [comment]
Are you able to enter the captcha even in the site? I think its kinda broken now.

**Comment by mrms123** [comment]
I could from the site

**Comment by dbn1972** [comment]
If they put the CAPTCHA on Mobile OTP ..?

**Comment by ad1tyas** [comment]
2captcha time bois?

**Comment by mrms123** [comment]
> If they put the CAPTCHA on Mobile OTP ..?

I don't think so - the OTPs are just spotty - we have seen that happen in the past too

**Comment by pallupz** [comment]
![image](https://user-images.githubusercontent.com/63504047/117426974-2649b880-af42-11eb-8f07-54c65a273b70.png)

at least we made to one of their issues

**Comment by mrms123** [comment]
Which repo is this?

Have to say, if this issue is the reason why they blocked it - then I am kinda happy about how responsive they are!

**Comment by manasshukla1** [comment]
Don't we have any other solution to this captcha? Anything? @pallupz

**Comment by pallupz** [comment]
Nope. If I could solve captchas, I would have been doing much better in life! lol

**Comment by ad1tyas** [comment]
> Nope. If I could solve captchas, I would have been doing much better in life! lol

You could try 2captcha integration. It may work. I've used it in the past.

**Comment by pallupz** [comment]
I dont want to. That might be "clearly illegal" territory

**Comment by pallupz** [comment]
Thanks for the name though, It'd be interesting learning activity

**Comment by samdsai** [comment]
Yes , Your right that is unethical too... !!

**Comment by ad1tyas** [comment]
> I dont want to. That might be "clearly illegal" territory

having a random person on the other side of the planet solve a captcha? Not sure what's illegal about that.

**Comment by pallupz** [comment]
You're right. But this is still India.

**Comment by pallupz** [comment]
Also, I dont thinks 2captcha is free

**Comment by ad1tyas** [comment]
> Also, I dont think 2captcha is free

Yep, it isn't. Run it on donations only access maybe.

**Comment by manasshukla1** [comment]
> > Also, I dont think 2captcha is free
> 
> Yep, it isn't. Run it on donations only access maybe.

yes exactly

**Comment by mrms123** [comment]
> You're right. But this is still India.

And not to forget the fact that booking needs a protected API access - which currently is not open

**Comment by pallupz** [comment]
Nonetheless, thanks a ton everyone for all the love and support 😇✌.

It was only a matter of time and this was taking quite a bit of effort in addition to my work anyway. If any of you guys figure this out, I'd really appreciate a quick message.

**Comment by mrms123** [comment]
> > Also, I dont think 2captcha is free
> 
> Yep, it isn't. Run it on donations only access maybe.

Not a good idea - even if it is donations, it gives it a commercial flavor - both the users and @pallupz might be in dangerous territory at that point.

**Comment by pallupz** [comment]
I think the first priority should be seeing if this is possible - free or not

**Comment by manasshukla1** [comment]
@pallupz Sure thing. We'll work on that.

**Comment by dbn1972** [comment]
Now million of users who are trying to book will have discomfort having a captcha to book ..for some users nuisance

**Comment by manankarani** [comment]
Although the party is over, there is still some ways, one such way is to use selenium to extract captcha image and create a popup so that user fills the details, and then maybe we can book.
But complete automation is not possible.

**Comment by madhu2504** [comment]
Can anyone enable Inspect element and see the details in Network section, while booking slot. I mean when you enter captcha in webpage and click on schedule or something, it must be calling the schedule API with some additional request headers or in body. Can anyone who goes to booking page can try and share the details here.  Ensure to open inspect element before booking a slot.

**Comment by manasshukla1** [comment]
@madhu2504 What will it do? I mean what is the use of this

**Comment by madhu2504** [comment]
> @madhu2504 What will it do? I mean what is the use of this

those request headers or  request parameters can be analysed to see if anything can be automated.

**Comment by subashjain** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/983641/117441681-65ccd080-af53-11eb-8b4d-279c719efac0.jpeg)

**Comment by subashjain** [comment]
For everyone wondering what the 4 digit secret code is

**Comment by harishvishwakarma** [comment]
The captcha can be downloaded and opened and the user can enter it, like they enter OTP.

**Comment by bbalegere** [comment]
There is a tool called jdownloader which has the ability to solve captchas.
For more details on how exactly to solve a captcha, this repo has some information
[Captcha Solver](https://github.com/cracker0dks/CaptchaSolver/blob/master/docs/howToSolve4DigitCaptchasWalkthrough.md)

**Comment by pallupz** [comment]
In short, send a POST request to: https://cdn-api.co-vin.in/api/v2/auth/getRecaptcha

From the response, do this:
```
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
from PIL import Image

resp = <response from POST request in json>

with open('captcha.svg', 'w') as f:
    f.write(resp['captcha'])

drawing = svg2rlg('captcha.svg')
renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")

img = Image.open('captcha.png')
img.show()
```
And take a user input to enter the captcha.

**Comment by pallupz** [comment]
Unfortunately, I wont be able to do this for a while. Actually paying job awaits. :|

**Comment by bbalegere** [comment]
Or try using Pillow and pytesseract, although I have no way to easily test this

**Comment by pallupz** [comment]
Who am I kidding, I couldn't resist. Latest version supports taking captcha.

**Comment by sharpant-dot** [comment]
.exe file is removed

**Comment by pallupz** [comment]
yea - there is an issue with image getting opened from exe. I'm getting the below error:
```
Can't setFont(Times-Roman) missing the T1 files?
Originally <class 'TypeError'>: makeT1Font() argument 2 must be str, not None
```
Python works though.  Will upload exe if I figure it out.

**Comment by bombardier-gif** [comment]
Can you please show the captcha user experience using your script? I want to see if I can integrate it or not

**Comment by pallupz** [comment]
not getting OTP

**Comment by samnahdi** [comment]
So how is it supposed to work with auto book (yes-please) option with the captcha feature....Is it suposed to prompt for captcha before booking...would it beep ?

**Comment by ameya2810** [comment]
Please tell me whether it will start working again ever or not

**Comment by pallupz** [comment]
Link to discord server : https://discord.gg/rCz8VdRB
