### ISSUE TITLE
Not receiving OTP

### ISSUE THREAD

**Issue by chintan-vunet** [pallupz/covid-vaccine-booking#125]
If I enter mobile number in cowin-webiste, I am able to get the OTP but from the script not able to receive OTP sms.

**Comment by pallupz** [comment]
Script is prompting to enter OTP? If yes, there's nothing more I can do. OTP generation is spotty in general.

**Comment by chintan-vunet** [comment]
Yes, but is there some change in the API there?
Because from the webiste it is sending me OTP

**Comment by harishvishwakarma** [comment]
Change secret key. Use the one from the website.

**Comment by pallupz** [comment]
key is fine. I'm getting OTP. Try after 10 minutes or so.

**Comment by monishthummala** [comment]
A simple hack:
Instead of using a protected API for generation of OTP, use the public API for generation. This removes the need to use a secret key. Surprisingly combination of public(generation)/protected(confirmation) seems to generate a usable token(can be used for booking as well. Tested with a random subject). I've used the existing APIs for the rest. This seems to have resolved the issue. It is consistent with the browser's behavior ( if it works there it'll work here)

**Comment by sud298** [comment]
Not receiving OTP.

**Comment by pallupz** [comment]
> 
> 
> A simple hack:
> Instead of using a protected API for generation of OTP, use the public API for generation. This removes the need to use a secret key. Surprisingly combination of public(generation)/protected(confirmation) seems to generate a usable token(can be used for booking as well. Tested with a random subject). I've used the existing APIs for the rest. This seems to have resolved the issue. It is consistent with the browser's behavior ( if it works there it'll work here)

Which URL are you using?

**Comment by monishthummala** [comment]
> > A simple hack:
> > Instead of using a protected API for generation of OTP, use the public API for generation. This removes the need to use a secret key. Surprisingly combination of public(generation)/protected(confirmation) seems to generate a usable token(can be used for booking as well. Tested with a random subject). I've used the existing APIs for the rest. This seems to have resolved the issue. It is consistent with the browser's behavior ( if it works there it'll work here)
> 
> Which URL are you using?

curl -X POST "https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"mobile\":\"9876543210\"}"
User-Agent header addition wasnt helpful, had to add accept n content-type headers as well. 
Added initial_request_header and passed the same for generation of token

        initial_request_header = {
                'accept': 'application/json',
                'Content-Type' : 'application/json'
        }

**Comment by pallupz** [comment]
and token from here works in other places too? thats super wierd

**Comment by monishthummala** [comment]
> dear lord! that does work!
> 
> EDIT: Wait, I'm not too sure

i added a dummy person with high availability filter(?) n i was able to book. this is all bfr this whole captcha thing came into play though. not sure now. bt ya shld work even after that i suppose

**Comment by pallupz** [comment]
Now I'm not getting OTP from either APIs

**Comment by monishthummala** [comment]
> Now I'm not getting OTP from either APIs

this is true with website as well. OTP has been kind of flaky today. have u checked if its working with the portal?

**Comment by pallupz** [comment]
I did. Dint work either. Usually that works.
