### ISSUE TITLE
where to write captcha code

### ISSUE THREAD

**Issue by archit-va** [pallupz/covid-vaccine-booking#127]

**Comment by pallupz** [comment]
in the terminall

**Comment by sagavkarmayur** [comment]
> in the terminall

I was trying to auto-book. But since the "captcha code" feature got introduced some time ago on booking confirmation page,
So i wasnt able to book.
Is there a work around possible for this ?
Much thanks, This script is quite phenominal!

**Comment by archit-va** [comment]
i couldnt write captcha it freezed

**Comment by archit-va** [comment]
after the png file opened i couldnt write anything in windows powershell

**Comment by archit-va** [comment]
please help

**Comment by pallupz** [comment]
My hands are tied man.. It usually works for me.

**Comment by archit-va** [comment]
![image](https://user-images.githubusercontent.com/69337316/117466911-d46c5700-af70-11eb-9763-e9542977a6f4.png)
PLEASE CHECK THIS WHY DOES THIS HAPPEN

**Comment by archit-va** [comment]
NO PLACE TO ENTER CAPTCHA
SHOULD I TRY OTHER TERMINAL?

**Comment by archit-va** [comment]
I HAVE DOWNLOADED ALL REQUIREMENTS

**Comment by archit-va** [comment]
should i use idle shell?

**Comment by pallupz** [comment]
I hope you were using virtual environment. Or try to create a fresh virtual env and try in there. I have just pushed the latest code.

**Comment by pallupz** [comment]
Not much different from original

**Comment by pallupz** [comment]
I dint mean virtual machine. I meant virtualenv in python.

**Comment by archit-va** [comment]
I saw how to enable virtual env and have installed all requirements in it in the folder. Will it surely work?

**Comment by archit-va** [comment]
or only using exe after installing pyinstaller would also work

**Comment by pallupz** [comment]
okay.. anyway OTPs arent working

**Comment by archit-va** [comment]
no they are

**Comment by pallupz** [comment]
lucky you! I'm not
