### ISSUE TITLE
captcha mechanism bug - No module named 'svglib'

### ISSUE THREAD

**Issue by axd123** [pallupz/covid-vaccine-booking#128]
Encountered the "No module named 'svglib'" error. 

`=================================== Note ===================================

Info from perhaps a previous run already exists in vaccine-booking-details.json in this directory.
IMPORTANT: If this is your first time running this version of the application, DO NOT USE THE FILE!
Would you like to see the details and confirm to proceed? (y/n Default y): y

================================= Info =================================

        beneficiary_dtls:
+-------+----------------+-------------+-----------+-------+----------------+
|   idx |        bref_id | name        | vaccine   |   age | status         |
+=======+================+=============+===========+=======+================+
|     1 | 98659092XXXXX | Wayne |           |    28 | Not Vaccinated |
+-------+----------------+-------------+-----------+-------+----------------+
        location_dtls:
+-------+-----------+--------------+
|   idx |   pincode |   alert_freq |
+=======+===========+==============+
|     1 |    400059 |          440 |
+-------+-----------+--------------+
|     2 |    400058 |          660 |
+-------+-----------+--------------+
|     3 |    400056 |          880 |
+-------+-----------+--------------+
|     4 |    400051 |         1100 |
+-------+-----------+--------------+
|     5 |    400008 |         1320 |
+-------+-----------+--------------+
        search_option   : 1
        minimum_slots   : 1
        refresh_freq    : 5
        auto_book       : no
        start_date      : 2
        vaccine_type    : None
        fee_type        : ['Free', 'Paid']

Proceed with above info? (y/n Default n): y
===================================================================================
Centers available in 400059 from 08-05-2021 as of 2021-05-07 19:32:53: 2
Centers available in 400058 from 08-05-2021 as of 2021-05-07 19:32:53: 2
Centers available in 400056 from 08-05-2021 as of 2021-05-07 19:32:53: 2
Centers available in 400051 from 08-05-2021 as of 2021-05-07 19:32:53: 2
Centers available in 400008 from 08-05-2021 as of 2021-05-07 19:32:53: 6
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                           | district   |   pincode |   available | date       | slots                                                                        |
+=======+================================+============+===========+=============+============+==============================================================================+
|     1 | Nair Hospital 2 (Age 18 To 44) | Mumbai     |    400008 |         435 | 08-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|     2 | BKC COVID Facility4 (18-44 Yr) | Mumbai     |    400051 |         496 | 08-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
----------> Wait 20 seconds for updated options OR
----------> Enter a choice e.g: 1.4 for (1st center 4th slot): 1.1
============> Got Choice: Center #1, Slot #1
Booking with info: {'beneficiaries': ['98659092925740'], 'dose': 1, 'center_id': 561567, 'session_id': 'c0d3343b-5825-4753-b94d-2d4426ea87ac', 'slot': '09:00AM-11:00AM'}
================================= GETTING CAPTCHA ==================================================
Booking Response Code: 200
No module named 'svglib'
===================================================================================
Centers available in 400059 from 08-05-2021 as of 2021-05-07 19:33:01: 3
Centers available in 400058 from 08-05-2021 as of 2021-05-07 19:33:01: 2
Centers available in 400056 from 08-05-2021 as of 2021-05-07 19:33:01: 2
Centers available in 400051 from 08-05-2021 as of 2021-05-07 19:33:01: 2
Centers available in 400008 from 08-05-2021 as of 2021-05-07 19:33:01: 6
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                           | district   |   pincode |   available | date       | slots                                                                        |
+=======+================================+============+===========+=============+============+==============================================================================+
|     1 | Nair Hospital 2 (Age 18 To 44) | Mumbai     |    400008 |         435 | 08-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|     2 | BKC COVID Facility4 (18-44 Yr) | Mumbai     |    400051 |         496 | 08-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|     3 | SEVEN HIILS 2 Age (18-44)      | Mumbai     |    400059 |         440 | 08-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:00PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
----------> Wait 20 seconds for updated options OR
----------> Enter a choice e.g: 1.4 for (1st center 4th slot): 2.1
============> Got Choice: Center #2, Slot #1
Booking with info: {'beneficiaries': ['98659092925740'], 'dose': 1, 'center_id': 561660, 'session_id': 'ef05c216-933d-489a-b10a-5a1f462bb9fa', 'slot': '09:00AM-11:00AM'}
================================= GETTING CAPTCHA ==================================================
Booking Response Code: 200
No module named 'svglib'
===================================================================================`

**Comment by pallupz** [comment]
Use Python 3.7 and install the dependencies in requirements.txt
