### ISSUE TITLE
Having issue with otp

### ISSUE THREAD

**Issue by vishwaphansal7** [pallupz/covid-vaccine-booking#129]
When completing the the captcha otp is not coming

**Comment by manasshukla1** [comment]
How do you run this project? It does not have a .exe file? @vishwaphansal7

**Comment by RaviPabari** [comment]
> How did you run this project? It does not have a .exe file? @vishwaphansal7

you have to run the .py script

**Comment by vishwaphansal7** [comment]
It's done by py script but having issues with otp after api update

**Comment by manasshukla1** [comment]
![11](https://user-images.githubusercontent.com/62873366/117465277-257b4b80-af6f-11eb-9b2e-a2c309e35114.PNG)

while I execute the .py file, it shows this error.    @vishwaphansal7 @RaviPabari

**Comment by vishwaphansal7** [comment]
> ![11](https://user-images.githubusercontent.com/62873366/117465277-257b4b80-af6f-11eb-9b2e-a2c309e35114.PNG)
> 
> while I execute the .py file, it shows this error.    @vishwaphansal7 @RaviPabari

You need to add your token given for the registration

**Comment by jatinguta** [comment]
> 
> 
> ![11](https://user-images.githubusercontent.com/62873366/117465277-257b4b80-af6f-11eb-9b2e-a2c309e35114.PNG)
> 
> while I execute the .py file, it shows this error. @vishwaphansal7 @RaviPabari

Install dependency

pip install -r requirements.txt

**Comment by vishwaphansal7** [comment]
Try python 3.7 and add your registration token
