### ISSUE TITLE
How do I generate my own secret key to call the protected API?

### ISSUE THREAD

**Issue by SarCode** [pallupz/covid-vaccine-booking#130]
[https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2
](API Setu Link)

How do I generate apiKey in API Setu?

**Comment by pallupz** [comment]
I just took that using Developer Mode. For some reason, it seems to be reusable.

**Comment by SarCode** [comment]
How do we activate the Developed Mode?

**Comment by pallupz** [comment]
Goto the portal using browser. When you reach the place to enter mobile number, before you do, press F12

**Comment by SarCode** [comment]
Ohh got it, you are mean when generating OTP, in network the secret is visible and you are just using that to generate more requests. 

I thought there was some dev mode on API Setu website.

Thanks for helping out, I will be closing this issue now.

**Comment by pallupz** [comment]
yup and happy to help
