### ISSUE TITLE
Feature Request : Is there a way I can modify it for pin code?

### ISSUE THREAD

**Issue by Logan1x** [pallupz/covid-vaccine-booking#16]
The district function is good, but it fetches center from very far, Is there a way, I can sort using pin code?

**Comment by Logan1x** [comment]
Does distance based sorting do similar work?

**Comment by pallupz** [comment]
I can show and sort by pincode. Without proper geolocation info, it's hard to calculate distance in a way that's reliable, simple, and free.

**Comment by mrms123** [comment]
@Logan1x I had tried doing a geo-location sort - the API is not returning proper lat long - returns it as an int, so most information is lost. 

This branch has some of that implemented - https://github.com/pallupz/covid-vaccine-booking/tree/feature/distance-sorting
It checks if the API is returning a float, if it doesn't, it pulls the latlong based on what geocodes provides for a given PIN code. You can specify your location either as lat long, or as PIN Code

**Comment by RohitSurwase** [comment]
How about requesting the pincode from user along with district and then filtering the list using the pincode? I think this would do the job.

**Comment by mrms123** [comment]
That's what the code on that branch does. District is non negotiable.
Pin Code can be entered with a --PINCode flag

**Comment by pallupz** [comment]
@mrms123 I had tried geocodes too. To verify that it has the correct coordinates against the pincodes, I tried looking up for pincodes in my area. Found that most locations were off by kilometers.

Are they displaying the locations correctly for you?

**Comment by pallupz** [comment]
Github: https://github.com/symerio/pgeocode
Data it refers to: https://download.geonames.org/export/zip/IN.zip

**Comment by mrms123** [comment]
Quite dependable in cities. Rural areas are a hit or miss, based on the
state.
In rural areas, you'll find them mapped to the central post office of the
region, and a bunch of them mapped to the same lat,long

**Comment by mrms123** [comment]
But then, Geocodes is what was used by the Govt as well - for the GST
waybill system - so I'm guessing that's the best available

**Comment by pallupz** [comment]
Ok. I am in a relatively developed township, but their results are off by at least 5 km. Similar results for towns/cities near me. I am not convinced that this is reliable, and hence apprehensive of implementing this.

**Comment by mrms123** [comment]
The alternate that we can do, is to use Google Geocoder API, and pull the latlong for every PIN Code and cache it. This is relatively more precise - cannot pull at runtime since the API needs an API key and is paid as well as limited.

**Comment by vatgarg** [comment]
https://github.com/pallupz/covid-vaccine-booking/pull/23

**Comment by heisenberg2208** [comment]
I think there should be some variation in the line https://github.com/pallupz/covid-vaccine-booking/blob/main/src/utils.py#L7

**Comment by pallupz** [comment]
Searching by pincodes have been implemented
