### ISSUE TITLE
On Windows client getting the following error...Support will be really appreciated

### ISSUE THREAD

**Issue by chaitnayamehta2005** [pallupz/covid-vaccine-booking#17]
C:\Users\chamehta\Downloads\Pyscripts>python covid-vaccine-slot-booking.py
Enter the registered mobile number: XXXXXXXXXX
Requesting OTP with mobile number XXXXXXXXXX..
**HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
Exiting Script
Press any key to continue . . .**

**Comment by pallupz** [comment]
Have you tried this: https://moreless.medium.com/how-to-fix-python-ssl-certificate-verify-failed-97772d9dd14c

**Comment by chaitnayamehta2005** [comment]
> Have you tried this: https://moreless.medium.com/how-to-fix-python-ssl-certificate-verify-failed-97772d9dd14c

On windows 10, tried to set the System Variable to following but still getting the same error.
PYTHONHTTPSVERIFY=0

**Comment by pallupz** [comment]
Unfortunately, there isn't much I can do about this from my end.
