### ISSUE TITLE
Unable to book slot

### ISSUE THREAD

**Issue by kannarao** [pallupz/covid-vaccine-booking#171]
Centers available in Bangalore Rural from 20-05-2021 as of 2021-05-20 09:11:05: 35
Centers available in Bangalore Urban from 20-05-2021 as of 2021-05-20 09:11:05: 37
Centers available in BBMP from 20-05-2021 as of 2021-05-20 09:11:05: 119
+-------+-------------------------------+------------+-----------+-------------+------------+----------------------------------------+
|   idx | name                          | district   |   pincode |   available | date       | slots                                  |
+=======+===============================+============+===========+=============+============+========================================+
|     1 | MANIPAL NORTHSIDE CANARA UNIO | BBMP       |    560003 |          47 | 20-05-2021 | ['10:00AM-12:00PM', '12:00PM-01:00PM'] |
+-------+-------------------------------+------------+-----------+-------------+------------+----------------------------------------+
AUTO-BOOKING IS ENABLED. PROCEEDING WITH FIRST CENTRE, DATE, and RANDOM SLOT.
============> Got Choice: Center #1, Slot #1
Booking with info: {'beneficiaries': ['xxxxx'], 'dose': 1, 'center_id': 569222, 'session_id': 'e4b2b63c-c93f-4bf1-bde0-290aad1ae39b', 'slot': '10:00AM-12:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
* Error performing wm_overrideredirect *
================================= ATTEMPTING BOOKING ==================================================
{'beneficiaries': ['98883421688630'], 'dose': 1, 'center_id': 569222, 'session_id': 'e4b2b63c-c93f-4bf1-bde0-290aad1ae39b', 'slot': '10:00AM-12:00PM', 'captcha': 'hywBF'}
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
b'{"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}'
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date. Please try another date or vaccination center."}
===================================================================================
Centers available in Bangalore Rural from 20-05-2021 as of 2021-05-20 09:11:16: 35
Centers available in Bangalore Urban from 20-05-2021 as of 2021-05-20 09:11:16: 37
Centers available in BBMP from 20-05-2021 as of 2021-05-20 09:11:16: 119
+-------+-------------------------------+------------+-----------+-------------+------------+----------------------------------------+
|   idx | name                          | district   |   pincode |   available | date       | slots                                  |
+=======+===============================+============+===========+=============+============+========================================+
|     1 | MANIPAL NORTHSIDE CANARA UNIO | BBMP       |    560003 |          47 | 20-05-2021 | ['10:00AM-12:00PM', '12:00PM-01:00PM'] |
+-------+-------------------------------+------------+-----------+-------------+------------+----------------------------------------+
AUTO-BOOKING IS ENABLED. PROCEEDING WITH FIRST CENTRE, DATE, and RANDOM SLOT.
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['xxxx'], 'dose': 1, 'center_id': 569222, 'session_id': 'e4b2b63c-c93f-4bf1-bde0-290aad1ae39b', 'slot': '12:00PM-01:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!

**Comment by kannarao** [comment]
I am trying from last one week but unable to book
It's always asking me to enter captcha but no result
Is there any update happened to "/appointment/schedule" api request payload

**Comment by himanshuhere** [comment]
I had the same issue when I logged myself into Cowin's official site and to script simultaneously. Try using script way only. Good luck!

**Comment by pallupz** [comment]
Auto-booking constantly tries for the first center and date sorted alphabetically and chronologically. If the first, and in this case, only center is full but the availability has not been updated in the backend (which should be handled by the Govt's API team), this will keep attempting to book it over and over again. Not much I can do here.
