### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by darrenpunnen** [pallupz/covid-vaccine-booking#19]
Hi Pallupz, really appreciate your efforts. Is there any way to reduce the frequency of updates? For some locations the slots get filled up in just a second or so, so it would be great if the slot availability could be checked   every second.

**Comment by pallupz** [comment]
Hi @darrenpunnen : I will try to parameterize the timeout

**Comment by mrms123** [comment]
@darrenpunnen Also take into account the fact that the API must be having some rate limiter configured on its end - based on IP address, to prevent DDoS attacks. More likely than not, 1 request a second might trigger that

**Comment by darrenpunnen** [comment]
Many thanks @pallupz, look forward to it. @mrms123 completely take your point, but honestly I don't think a request per second might trigger that. Certainly, there are codes that are already doing this. Availability would not have been so difficult otherwise :)

**Comment by pallupz** [comment]
Hi @darrenpunnen : The latest version allows for timeout customization. I have set the minimum allowed value as 5 seconds. Maximum would be upto the user.

**Comment by darrenpunnen** [comment]
Thank you so so much @pallupz! It works perfectly and I was able to book 3 slots immediately.

**Comment by chaaip** [comment]
> Hi @darrenpunnen : I will try to parameterize the timeout

It would be nice if you could set it to 1-sec ping for a few minutes (say 20 minutes max) and then it reverts to whatever might make it look not suspicious.
