### ISSUE TITLE
OTP not validating

### ISSUE THREAD

**Issue by Dugdudada** [pallupz/covid-vaccine-booking#199]
otp is not getting validated .

**Comment by thesct22** [comment]
```
Enter OTP (If this takes more than 2 minutes, press Enter to retry): 181596
Validating OTP..
Unable to Validate OTP
Response: {"message": "Endpoint request timed out"}
```

**Comment by Dugdudada** [comment]
yes getting this error

**Comment by sam-mitkayal** [comment]
This fixed the error:-
    base_request_header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66',
        'origin': 'https://selfregistration.cowin.gov.in',
        'referer': 'https://selfregistration.cowin.gov.in/'
    }

**Comment by pallupz** [comment]
it should be fixed in the latest code
