### ISSUE TITLE
Can you add alternative of winsound for linux users?

### ISSUE THREAD

**Issue by Logan1x** [pallupz/covid-vaccine-booking#2]
Hey, I am trying to use this script for Linux but due to unavailability of winsound for Linux distro, I am unable to run the script.

Here are some of the solution you can try,

1. https://stackoverflow.com/questions/12354586/python-what-are-the-nearest-linux-and-osx-equivalents-of-winsound-beep
2. https://stackoverflow.com/questions/13150267/convert-winsound-to-a-linux-platform

**Comment by pallupz** [comment]
Sure, will try

**Comment by pallupz** [comment]
Almost every solution I see brings in a new third-party package dependency - which I really don't want to do. And so for now, I have tabled this. Also, I myself have to first setup a Linux VM to test it out. 

Meanwhile, please feel free to fork this and edit it. If you do edit it in a cross-platform way, I would be glad to merge that into this.

**Comment by pallupz** [comment]
I have incorporated cross platform support. Could you please try running the python file now?

Please note, you will need to install the beep package on linux to run the beep command. You can install by giving the command
```
sudo apt-get install beep
```

**Comment by Logan1x** [comment]
@pallupz Thanks for the efforts, Can you please tell me source of beep package? 

I found this (https://github.com/johnath/beep) but I am not sure.

I am asking this because I am an arch Linux user and apt install doesn't work for me. 

Thanks again for the efforts :)

**Comment by pallupz** [comment]
Hi - I have no idea. I am primarily a Windows user and just modified the code in a way that _should_ be 'runnable' on Linux. Sorry I couldn't be of more help.

**Comment by Logan1x** [comment]
No worries, Thanks to your script, my first dose is now booked :)
