### ISSUE TITLE
Unable to Validate OTP

### ISSUE THREAD

**Issue by rupamcroy** [pallupz/covid-vaccine-booking#203]
it gets stuck after entering otp. and receive a end point timeout error.

**Comment by gpradeepjain** [comment]
https://github.com/pallupz/covid-vaccine-booking/issues/199

**Comment by rupamcroy** [comment]
can you please let me know where to enter the below code???

base_request_header = {
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66',
'origin': 'https://selfregistration.cowin.gov.in',
'referer': 'https://selfregistration.cowin.gov.in/'
}

**Comment by Yugalmodi** [comment]
> covid-vaccine-slot-booking.py
> #base_request_header = {
> # 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
> #}
> base_request_header = {
> 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66', 'origin': 'https://selfregistration.cowin.gov.in', 'referer': 'https://selfregistration.cowin.gov.in/'
> }

above fix is not working. @pallupz please help to resolve this

**Comment by akuma2519** [comment]
Atleast for me this fix is working well from last 30mins.. @pallupz @sam-mitkayal

**Comment by Yugalmodi** [comment]
working now, I deleted old code and applied the above solution in fresh code.

**Comment by gitdheeraj** [comment]
hi @Yugalmodi  @akuma2519  i have no idea where to edit this code ? Please help me with this as my booking is on 2:30pm. Please help :(

**Comment by gitdheeraj** [comment]
@Yugalmodi Thank you :)

**Comment by pallupz** [comment]
it should be fixed in the latest code
