### ISSUE TITLE
too many requests

### ISSUE THREAD

**Issue by rheak01** [pallupz/covid-vaccine-booking#219]
Unable to Generate OTP
429 {
 "error": "Too Many Requests"
}

@pallupz please help

**Comment by rheak01** [comment]
can anybody help asap

**Comment by rheak01** [comment]
also, why is the otp being asked after 5 mins again and again it used to be after 15mins , earlier??

**Comment by manojagarwal68** [comment]
Yeah, have noticed this issue today. Not sure when it started. Are others facing this issue as well?

**Comment by pallupz** [comment]
There isn't much documentation on the API but my guess is you're hitting the API rate limiter perhaps

**Comment by aascagarwal** [comment]
Here is my thought..
As per API the limit is 100 request per 5 minutes
Which is 1 request per 3 seconds..
Even though the minimum refresh frequency is set to 5 secs. There is also a request in parallel to verify the beneficiary for token expiration, making it 2 requests per 5 secs and 100 request in 2.5 minutes which voilates the api rate limit

**Comment by archit-va** [comment]
@aascagarwal  you are so smart

**Comment by aascagarwal** [comment]
Is that sarcastic?

**Comment by archit-va** [comment]
No

**Comment by pallupz** [comment]
the math doesn't make a lot of sense (assuming rate limiter is applicable for ALL endpoints _and_ hits across all endpoints are counted together in their calculation) but there isn't much we can do from a code point of view either.
