### ISSUE TITLE
syntax error when executing src/covid-vaccine-slot-booking.py

### ISSUE THREAD

**Issue by vinayd2** [pallupz/covid-vaccine-booking#22]
There appears to be stray "f" introduced in a few lines
eg:  `request_header = {"Authorization": f"Bearer {token}"}`

**Comment by pallupz** [comment]
Those are not strays. It's python f-strings. Works from Python 3.6+ for string substitution.

**Comment by vinayd2** [comment]
Thanks. n00b mistake in report. works as expected with python 3.8
