### ISSUE TITLE
Unable to Validate OTP

### ISSUE THREAD

**Issue by ramesh-s-bisht** [pallupz/covid-vaccine-booking#225]
Hi, I'm unable to validate the OTP. The error says - {"message": "Endpoint request timed out"}

Any idea if this is happening due to too many request from the API. And if any solution around the same?

Thanks
Ramesh

**Comment by sumantro93** [comment]
I am experiencing the same

**Comment by sumantro93** [comment]
> Hi, I'm unable to validate the OTP. The error says - {"message": "Endpoint request timed out"}
> 
> Any idea if this is happening due to too many request from the API. And if any solution around the same?
> 
> Thanks
> Ramesh
This worked for me

https://github.com/pallupz/covid-vaccine-booking/issues/214#issuecomment-847923579

**Comment by pallupz** [comment]
Use the latest code

**Comment by ramesh-s-bisht** [comment]
Thanks, used the latest code and it works.
