### ISSUE TITLE
Is this legal ???

### ISSUE THREAD

**Issue by nbhupendra** [pallupz/covid-vaccine-booking#24]
Production apis is not open for public uses. So just wanted to check if that is legal?

**Comment by krishna1831** [comment]
Is this legal?

**Comment by krishna1831** [comment]
> Is this legal?

    But private api is being used ryt?

**Comment by p4i1** [comment]
> > Is this legal?
> 
> ```
> But private api is being used ryt?  Won't I get any legal trouble after booking? 
> ```
> 
> Had anyone got vaccine successfully without any issue using this method?

yes
