### ISSUE TITLE
error fetching OTP API:Not Found

### ISSUE THREAD

**Issue by prashm31** [pallupz/covid-vaccine-booking#244]
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/xxxxxxxxxx
Requesting OTP with mobile number xxxxxxxxxx..
error fetching OTP API:Not Found

**Comment by pallupz** [comment]
you should probably post this on bombardier repo

**Comment by prashm31** [comment]
Thank you bro
