### ISSUE TITLE
unable to fetch beneficiaries

### ISSUE THREAD

**Issue by meghaboggaram** [pallupz/covid-vaccine-booking#27]
Im getting this error after entering OTP:

Fetching registered beneficiaries.. 
Unable to fetch beneficiaries
401
Unauthenticated access!
sh: pause: command not found
object of type 'NoneType' has no len()
Exiting Script
sh: pause: command not found

where am I going wrong?

**Comment by pallupz** [comment]
Are you using a registered mobile number with beneficiaries already added? If yes, this shouldn't fail.

**Comment by meghaboggaram** [comment]
I am using a registered number with beneficiaries added.. this error is on my mac when I try to run the python script.

now I am running your windows executable with the same phone number and its working fine.

**Comment by meghaboggaram** [comment]
does it not run on mac?

**Comment by pallupz** [comment]
No idea - I don't have a mac. Have only tested this on Windows. Regardless, ideally it shouldn't have failed that early.

**Comment by vinayd2** [comment]
I got it working on Mac with Python 3.8.2. 
Note: Pyhon 2 is default on MacOS. So invoke the script with `python 3 src/covid-vaccine-slot-booking.py`

to set up requirements use `python3 -m pip install -r requirements.txt`

**Comment by meghaboggaram** [comment]
@vinayd2 I'm running with python 3.9.5 and with all requirements installed using pip. Otherwise the script wont be running to ask my phone number and OTP.
I'm missing something else..

**Comment by pallupz** [comment]
If you're able to see beneficiaries on portal with the same mobile number, this should work too. They are identical in functionality.
