### ISSUE TITLE
Suggestion: Better make this a website than a Python script

### ISSUE THREAD

**Issue by subins2000** [pallupz/covid-vaccine-booking#3]
Nice work on automating the booking process. But I think this is unfair. This puts programmers and people with technical expertise at an advantage over everyone else. Currently the cowin platform appointment is based on luck for everyone. With a script, programmers have edge over everyone else.

But at some point, someone would have made this anyway and kept it private. At least you made it open source. Thanks for that!

It would be more equitable if this is a website for python-terminal-illiterate people. An alternative frontend for Cowin with these features you added.

**Comment by pallupz** [comment]
I'd love make this a website but as you could guess from the current layout, I'm not a frontend guy. Unfortunately, don't have the know-how to do it either.

As for the advantage part, you're at least partially correct I guess. I started to look into this when I myself got frustrated trying to find an appointment. Hopefully this helps more people.
