### ISSUE TITLE
No beep notification when the token expires

### ISSUE THREAD

**Issue by amiteshs0505** [pallupz/covid-vaccine-booking#30]
No beep notification when the token expires. Also what is the time in which the token expires and what does it depend on? is it possible to increase this timer?

**Comment by vatgarg** [comment]
Its already resolved in this fork , main branch

https://github.com/vatgarg/covid-vaccine-booking

**Comment by pallupz** [comment]
@amiteshs0505 This is supposed to beep on token expiry. What behavior are you seeing? Also, would you have screenshots to share?

**Comment by amiteshs0505** [comment]
@vatgarg @pallupz it is fixed in the main branch. can hear the beep now in case of token expiry. Can you let me know how does this token expiry work?
Is it the time in which u get logged out from the portal in case of idle?

**Comment by pallupz** [comment]
From my experience, it seems to expire every 15mins or so
