### ISSUE TITLE
how to modify code to search for 18-44 available slots only

### ISSUE THREAD

**Issue by ariaraj** [pallupz/covid-vaccine-booking#32]
Is there a way we can restrict the search only for 18-44 age group?

**Comment by vatgarg** [comment]
Its already resolved in this fork , main branch

https://github.com/vatgarg/covid-vaccine-booking

**Comment by pallupz** [comment]
@ariaraj - The script only shows slots that are applicable to the age of the beneficiary. Is that what you were looking for?
