### ISSUE TITLE
Script gets exited when there is no response from fetch slot API

### ISSUE THREAD

**Issue by agabhane** [pallupz/covid-vaccine-booking#33]
Due to heavy load sometimes the API used for fetching the slots availability returns no response.
As a result the exe program gets exited with beep saying NoneType cannot be iterated.

User have to start whole script again.

**Comment by vatgarg** [comment]
Its already resolved in this fork , main branch

https://github.com/vatgarg/covid-vaccine-booking

**Comment by pallupz** [comment]
I will try to address it here as well

**Comment by vatgarg** [comment]
@pallupz I opened a PR, if you could merge.

**Comment by vatgarg** [comment]
Aw okay. Yea please maintain the quality, but dont block the conversation. :) Well, i didnt realise, i was just extracting bigger methods of your code to smaller one :)

**Comment by vatgarg** [comment]
@pallupz  But Anyways, you were the author of the code, and it worked. So, no regrets. Thanks anyways..

**Comment by pallupz** [comment]
@agabhane : Did you happen to take a screenshot of the issue? This shouldn't have happened. Even better, if you're able to reproduce it, please do let me know which state/district you had used.

**Comment by agabhane** [comment]
Hi @pallupz ,

I did not take the screenshot. Anyways the issue got resolved after takig update from  https://github.com/vatgarg/covid-vaccine-booking.
FYI. I was checking the slots for Maharashtra -> Pune

**Comment by agabhane** [comment]
Hi @pallupz 
Booked the slots two times. Worked really well.

Kudos.

**Comment by pallupz** [comment]
Thank you for coming back to mention this. That really mean a lot! 👍

**Comment by pallupz** [comment]
Please feel free to spread the word a bit, if you don't mind.
