### ISSUE TITLE
Error on both Mac & Linux

### ISSUE THREAD

**Issue by harishkadamudi** [pallupz/covid-vaccine-booking#34]
Following your instruction to run the scripts, I am on Linux.

Getting error when I ran python src/covid-vaccine-slot-booking.py

File "src/covid-vaccine-slot-booking.py", line 20
    request_header = {"Authorization": f"Bearer {token}"}

**Comment by harishkadamudi** [comment]
Sorry, when I ran with python3. it worked

**Comment by vatgarg** [comment]
better version in this fork , main branch

https://github.com/vatgarg/covid-vaccine-booking
