### ISSUE TITLE
Showing a non-zero number of centers available with no viable options. Should show 0 mostly?

### ISSUE THREAD

**Issue by whizzkky** [pallupz/covid-vaccine-booking#36]
![image](https://user-images.githubusercontent.com/5616854/117137699-b8798180-adc7-11eb-8b5e-4b5875d7d9b2.png)

This is what I see when I run the code as is. But when I change 'tomorrow' in this line (in check_calendar() in utils.py) ->
resp = requests.get(base_url.format(district['district_id'], tomorrow), headers=request_header)

to 'today' then that 105 number becomes 0. Not sure why this is happening. I was running this modified version and the slots that opened up did not show up while this was running.

**Comment by pallupz** [comment]
105 is the number of all available options regardless of age restrictions or other parameters. In all likelihood, none of those will be viable for your beneficiary. You can verify this by logging on to the official portal.

**Comment by whizzkky** [comment]
Yes that's quite likely. But as per the readme, it's generally supposed to show 0 eligible centers I thought?

**Comment by pallupz** [comment]
I should probably update the readme. The reason I kept the number there is so that it reassures user that the search is coming up with some result - but not any viable ones.

**Comment by whizzkky** [comment]
Alright, got it, thanks!

**Comment by pallupz** [comment]
Please feel free to spread the word a bit, if you don't mind.
