### ISSUE TITLE
Unable to confirm slots due to rush

### ISSUE THREAD

**Issue by sharpant-dot** [pallupz/covid-vaccine-booking#39]
Hi ,

Can we modify this code to make it automatically book the slots , any location , any time , any date?

Regards,
Prasanth

**Comment by pallupz** [comment]
It is possible but that would have far reaching consequences

**Comment by sharpant-dot** [comment]
Thank you for responding , If you are talking about only distance, i am ok , since i am already selecting district as BBMP, i dont mind travelling within the BBMP limits, also the slots are not opening up everywhere, only in few places for 18- 44 at a time.

**Comment by pallupz** [comment]
I understand that. There's also the problem of how do I test and make sure this works - this is all live. I can try to provide a "beta" version in a separate branch.

**Comment by sharpant-dot** [comment]
Agree to your point, separate branch make sense

**Comment by pallupz** [comment]
This branch has the feature: https://github.com/pallupz/covid-vaccine-booking/tree/feature/auto-book

I tested it and it does work - books first available center, date, and slot. Please do let me know if you run into any issues.
