### ISSUE TITLE
look for slots starting a specific date

### ISSUE THREAD

**Issue by amiteshs0505** [pallupz/covid-vaccine-booking#43]
Is it possible to add support for looking for slots starting from a user provided date ? would be helpful for ppl to book second dose after 28 days

**Comment by sharpant-dot** [comment]
slots might never open up that much in advance.. it generally opens with in the next 3 - 7 days max..  in Banglore at least..

**Comment by amiteshs0505** [comment]
Yup tru.. suppose my 2nd dose is due on june 1 and i start looking 3-4 days before and i end up booking slot before june 1 .. i know we can cancel and try again after a few days ... Is this is too much to as for and not worth the effort , ignore this request

**Comment by pallupz** [comment]
Yup. Discarded it for the same reason.

Related reply: https://github.com/pallupz/covid-vaccine-booking/issues/1#issuecomment-830586165
