### ISSUE TITLE
user choice for Covishield or Covaxin

### ISSUE THREAD

**Issue by bitshiftr** [pallupz/covid-vaccine-booking#52]
Can we have user input for choosing Covaxin vs Covishield?

**Comment by madhu2504** [comment]
is this feature available now?

**Comment by pallupz** [comment]
not yet for dose 1 takers

**Comment by pallupz** [comment]
I dont see any APIs to list the available vaccine types. Only way around I see is a hardcoded list  - which is not ideal.

**Comment by bitshiftr** [comment]
> I dont see any APIs to list the available vaccine types. Only way around I see is a hardcoded list - which is not ideal.

agreed, but given that for the foreseeable future, we will only have 2 vaccine types, it will be great for those of us who are keen on taking covaxin

**Comment by pallupz** [comment]
latest version suppots this feature

**Comment by bitshiftr** [comment]
you are awesome - thanks!

**Comment by pallupz** [comment]
Happy to help. Please feel free to spread the word, if you dont mind. Link: https://www.linkedin.com/feed/update/urn:li:activity:6794138228464193536/
