### ISSUE TITLE
Getting error on line 52

### ISSUE THREAD

**Issue by aanchalmaheshwari** [pallupz/covid-vaccine-booking#6]
Hi,

Thanks for creating this script. I have very limited working knowledge of Python and hence pasting the error I am getting on line 52.

python ./covid-vaccine-slot-booking.py

File "./covid-vaccine-slot-booking.py", line 52
CALENDAR_URL += f"&vaccine={vaccine_type}**"**
SyntaxError: invalid syntax

It is showing a error on " after } . Could you let me know how to resolve this?

**Comment by aanchalmaheshwari** [comment]
Python version : Python 2.7.16 (default, Dec 21 2020, 23:00:36)

**Comment by mrms123** [comment]
This code is in a Python 3 syntax

**Comment by pallupz** [comment]
You've to install and use Python 3.
F-strings won't work in Python 2.
