### ISSUE TITLE
Unable to Create OTP

### ISSUE THREAD

**Issue by sagarspatil** [pallupz/covid-vaccine-booking#62]
`Enter the registered mobile number: 75075XXXXX
Requesting OTP with mobile number 75075XXXXX..
Unable to Create OTP
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: yc_80Zck48I4dhhO9yh05XeWccrv-5NCqTfq760qr_BCu7I0WGx5yw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`

**Comment by pallupz** [comment]
Please use the latest available version
