### ISSUE TITLE
Secret for OTP hardcoded

### ISSUE THREAD

**Issue by ApricotJaguar** [pallupz/covid-vaccine-booking#66]
I noticed that the secret for the OTP generation is hard-coded. Wouldn't the secret change for an individual?

**Comment by pallupz** [comment]
I dont think so since its working for people. Also, I couldn't find exactly how they are calculating that field.

**Comment by mrms123** [comment]
This is essentially a goof-up by the CoWIN portal - exposing their API secret key
Every application is supposed to have its own API secret key, to authenticate it, and also identify which application it is. Unfortunately, for the CoWIN website, it's in console

In reality, if you're building an app like this - with protected API access, you're supposed to obtain your own secret API key for the app - not for the user.
