### ISSUE TITLE
Unable to generate OTP

### ISSUE THREAD

**Issue by AmoghDabholkar** [pallupz/covid-vaccine-booking#69]
As can be seen in the below-attached screenshot, there's some error in generating the OTP. Was working fine until yesterday afternoon. 

Steps to reproduce the error - 
1. cd src
2. python covid-vaccine-slot-booking.py
3. Enter your phone number.

![image](https://user-images.githubusercontent.com/30367866/117255664-87508e00-ae67-11eb-9d4d-6899fe0e514f.png)

**Comment by mah2001** [comment]
use the latest version it will work

**Comment by AmoghDabholkar** [comment]
Tried using the latest pull, working now. Closing the issue.
