### ISSUE TITLE
Facing Max retries exceeded ERROR after 2 minutes

### ISSUE THREAD

**Issue by banerjeedeep** [pallupz/covid-vaccine-booking#73]
Great code. But facing this : 
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/beneficiaries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021DE13D2E08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Please help !!

**Comment by pallupz** [comment]
I'm not 100% sure but, in API Details, read the first block of text at the very top: https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2

**Comment by pallupz** [comment]
Consider setting your refresh frequency accordingly

**Comment by ayush1810** [comment]
> these APIs are subject to a rate limit of 100 API calls per 5 minutes per IP. 

I am setting a refresh frequency of 30 seconds, still receiving this error after couple of search calls.

![cowin](https://user-images.githubusercontent.com/14912708/117266642-1911c880-ae73-11eb-9d50-1e6668f67dd2.png)

@pallupz  Can you please look into this?

**Comment by pallupz** [comment]
@ayush1810 - Could you wait for 10 minutes before attempting again? May be previous attempts are being cumulatively added. 

There isn't much I can do about this from a code perspective. We hit the beneficiaries URL after every calendar update just to make sure that the token is still valid.
