### ISSUE TITLE
script hung and doesn't update when choosing the search from date option

### ISSUE THREAD

**Issue by amiteshs0505** [pallupz/covid-vaccine-booking#74]
![Capture](https://user-images.githubusercontent.com/83693701/117264173-9be55400-ae70-11eb-98d3-d26f1facc5d4.PNG)

script hung and doesn't update when choosing the search from date option

**Comment by pallupz** [comment]
Did you try restarting and is the issue still there?

**Comment by amiteshs0505** [comment]
working now. closing this
