### ISSUE TITLE
Cancelled appointment is being considered as 2nd dose

### ISSUE THREAD

**Issue by sharpant-dot** [pallupz/covid-vaccine-booking#79]
Hi i was able to book the appointment, but it got cancelled by the hospital , in the program ,vaccine is prefilled and is searching for a dose2 and is failing because dose 1 in not complete. 

Booking response code 400

**Comment by pallupz** [comment]
Ohk.. In the official portal are you marked as vaccinated or partially vaccinated?

**Comment by sharpant-dot** [comment]
it says dose - appointment not scheduled..

**Comment by pallupz** [comment]
okay.. let me check

**Comment by pallupz** [comment]
The latest version I have just committed should fix this issue

**Comment by pallupz** [comment]
If this app

**Comment by pallupz** [comment]
If this script was useful, please feel free to spread the word a bit - if you don't mind. Link: https://www.linkedin.com/feed/update/urn:li:activity:6794138228464193536/

**Comment by sharpant-dot** [comment]
Unable to Create OTP
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>







Press any key to continue . . .

**Comment by AkhilmsAchu** [comment]
poli sanam, steel ;)

**Comment by pallupz** [comment]
@sharpant-dot It shudnt be an issue at the moment
