### ISSUE TITLE
New issue: Porgram taps out after trying one round

### ISSUE THREAD

**Issue by sixfooter** [pallupz/covid-vaccine-booking#80]
Getting this msg after one round of 15mins or probably lesser time. 
+++++++++++++++++
Try for a new Token? (y/n Default y): y
Requesting OTP with mobile number xxxxxxx..
Unable to Create OTP
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: KNZjNfiAxHnDP6lR_NLhpRdjtEPLkjI2p0tKapzdOVWn2yNvZg26rA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
Press any key to continue . . .
Enter OTP:

**Comment by pallupz** [comment]
Are you using the latest version?

**Comment by sixfooter** [comment]
Yup,as latest as 3:03PM

**Comment by pallupz** [comment]
That's weird. It's working for me.

**Comment by sixfooter** [comment]
it has tapped out once till now and has worked once after posting the original msg

**Comment by pallupz** [comment]
yea it stopped working

**Comment by pallupz** [comment]
well, no.. this is weird. its working again now. I guess fetching the beneficiary fails sometimes

**Comment by sixfooter** [comment]
yes, there is something weird going on.. will post back if /when i see it again.

**Comment by tanmecolor** [comment]
> Getting this msg after one round of 15mins or probably lesser time.
> +++++++++++++++++
> Try for a new Token? (y/n Default y): y
> Requesting OTP with mobile number xxxxxxx..
> Unable to Create OTP
> <TITLE>ERROR: The request could not be satisfied</TITLE>
> # 403 ERROR
> ## The request could not be satisfied.
> Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> 
> Generated by cloudfront (CloudFront)
> Request ID: KNZjNfiAxHnDP6lR_NLhpRdjtEPLkjI2p0tKapzdOVWn2yNvZg26rA==
> 
> Press any key to continue . . . Enter OTP:

This error happens if you are accessing the server from an IP outside India or via ( VPN /TOR etc .. )

**Comment by sixfooter** [comment]
Hmm. I am on a vpn but its on an india server.

**Comment by pallupz** [comment]
Script is working. Closing the ticket for now.

**Comment by sixfooter** [comment]
Getting again , pasting ... 


Centers available in BBMP from 06-05-2021 as of 2021-05-06 16:36:44: 24
Token is INVALID.. Next update in 1 seconds..
Try for a new Token? (y/n Default y): y
Requesting OTP with mobile number xxxx..
Unable to Create OTP
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>







Press any key to continue . . .

**Comment by sparshSinghal** [comment]
Facing this issue as well.
