### ISSUE TITLE
Re-scheduling of appointment

### ISSUE THREAD

**Issue by aswinjayan94** [pallupz/covid-vaccine-booking#86]
Hey buddy! Thanks a lot for your code, it's very helpful. 
I'm trying to understand if the code works for people who have already booked an appointment, but couldn't get vaccinated (technical issues in cowin sent me to non-functional vaccination centres, TWICE!). Would the code be able to re-schedule for people who already have a back-dated appointment?

If not, could you give me a hint as to what part of the code I could modify to make it work?

**Comment by aswinjayan94** [comment]
Forgot to mention that I missed a slot that was opened at around 3.30pm in pincode 560030. I examined the logs, found that the code wasn't able to detect the opening. (my frequency is every 5 seconds)

**Comment by amoghjay** [comment]
Yes same even I missed that slot , the code couldn't detect the opening ( I used filter by State and District option)

**Comment by aswinjayan94** [comment]
> Yes same even I missed that slot , the code couldn't detect the opening ( I used filter by State and District option)

are you also trying to re-schedule?

**Comment by sharpant-dot** [comment]
cancel and rebook

**Comment by aswinjayan94** [comment]
> cancel and rebook

The appointment time is yesterday dude. The website isn't allowing me to cancel because of that

**Comment by amoghjay** [comment]
> 
> 
> > Yes same even I missed that slot , the code couldn't detect the opening ( I used filter by State and District option)
> 
> are you also trying to re-schedule?

No

**Comment by pallupz** [comment]
There is an [rescheduleAppointment](https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2#/Vaccination%20Appointment%20APIs/rescheduleAppointment) API. I dont know if it will work for you.

Do you know how to use Developer Mode on Browser? If yes, could you login, and reach the beneficiaries page, and send me the responses for the whole thing? Please make sure to remove any personally identifiable information.

**Comment by aswinjayan94** [comment]
> There is an [rescheduleAppointment](https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2#/Vaccination%20Appointment%20APIs/rescheduleAppointment) API. I dont know if it will work for you.
> 
> Do you know how to use Developer Mode on Browser? If yes, could you login, and reach the beneficiaries page, and send me the responses for the whole thing? Please make sure to remove any personally identifiable information.

alright i'll try that, thanks @pallupz
