### ISSUE TITLE
Message for the author

### ISSUE THREAD

**Issue by Ashikarames98** [pallupz/covid-vaccine-booking#88]
I think you're an amazing coder! Really impressed with this code! Teach me coding Senpai! :(

**Comment by sharpant-dot** [comment]
https://www.buymeacoffee.com/pallupz - Please donate if you have benefitted.  i just did. or share his linkedin handle

**Comment by pallupz** [comment]
@Ashikarames98 I really am not and this is not too difficult either. Just takes some practice is all. Nonetheless, thank you for your kind words!

**Comment by lets-get-vaccinated** [comment]
> https://www.buymeacoffee.com/pallupz - Please donate if you have benefitted. I just did. or share his linkedin handle
@sharpant-dot : How many trials did it take for you for successful booking? I have been trying with the latest codebase, there have been 3 announcements but no prompt/appointment. Any advice?
