### ISSUE TITLE
dates should be auto-looked (from today to whenever slots available in future). 

### ISSUE THREAD

**Issue by subashjain** [pallupz/covid-vaccine-booking#90]
Dates should be auto-looked,as of whenever the slots are open. pls add this feature. Also, allow us to select our age group.

**Comment by sharpant-dot** [comment]
the code will select the age group based on ur registration

**Comment by subashjain** [comment]
ohh thats cool, thanks !

**Comment by aswinjayan94** [comment]
> Dates should be auto-looked,as of whenever the slots are open. pls add this feature. Also, allow us to select our age group.

with the rate at which slots are getting booked these days, i think even the time saved not searching for future dates could help

**Comment by subashjain** [comment]
> > Dates should be auto-looked,as of whenever the slots are open. pls add this feature. Also, allow us to select our age group.
> 
> with the rate at which slots are getting booked these days, i think even the time saved not searching for future dates could help

yes this is also true

**Comment by pallupz** [comment]
@subashjain I dint understand the requirement here

**Comment by subashjain** [comment]
@pallupz i meant, the scrpit shouldnt ask us the dates. It should automatically books the slots whenever they get opened.
