### ISSUE TITLE
Why not save preferences to a .json file?

### ISSUE THREAD

**Issue by vamsee** [pallupz/covid-vaccine-booking#93]
just wondering, why not save preferences to a .json file in the folder and pick it up instead of entering all the options everytime we start the script? Deleting the json file could be flag to ask all the questions again 🤔

**Comment by pallupz** [comment]
That is possible too. Please feel free to fork and develop. If its working and a good code, I will try to merge it in here. Unfortunately, time is the main problem.

**Comment by ayush1810** [comment]
++

**Comment by pallupz** [comment]
This has been implemented

**Comment by pallupz** [comment]
In the latest version
