### ISSUE TITLE
Auto booking feature not working its showing slots availability of today which are already booked

### ISSUE THREAD

**Issue by Sidbeheraunsw** [pallupz/covid-vaccine-booking#94]

**Comment by pallupz** [comment]
Please share the screenshot or logs.

**Comment by sharpant-dot** [comment]
you have to type - "yes-please" , not just yes

**Comment by Sidbeheraunsw** [comment]
![WhatsApp Image 2021-05-06 at 6 12 23 PM](https://user-images.githubusercontent.com/71659019/117302066-e084e580-ae98-11eb-90ab-818c91c3c093.jpeg)

**Comment by Sidbeheraunsw** [comment]
Can we have preference for slot 3 or 4 because slot 1 gets booked quickly

**Comment by pallupz** [comment]
I will try to add that option

**Comment by pallupz** [comment]
slot selection has been randomized. It will still try for the first center and date - sorted ascending
