### ISSUE TITLE
KeyError: 'centers' 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dbsheta** [pallupz/covid-vaccine-booking#95]
After running the script for some time, I get this error:
```python
{'sessions': []}
'centers'
-e 
Traceback (most recent call last):
  File "/Users/username/Downloads/covid-vaccine-booking-main/src/utils.py", line 93, in check_calendar_by_district
    print(f"Centers available in {location['district_name']} from {start_date} as of {today.strftime('%Y-%m-%d %H:%M:%S')}: {len(resp['centers'])}")
KeyError: 'centers'
'NoneType' object is not iterable
Exiting Script
```

**Comment by pallupz** [comment]
I think the you may have received an invalid response in that call. I will try to add an exception handling for this.

If you retry, that should work.

**Comment by dbsheta** [comment]
I added below at line 93 in utils.py and it's working fine since then.

```python
if ('centers' not in resp):
    continue
```

**Comment by pallupz** [comment]
I will make an equivalent change.

**Comment by jiteshlalwani** [comment]
Not working even after adding:

if ('centers' not in resp):
    continue

**Comment by pallupz** [comment]
change in two places:
![image](https://user-images.githubusercontent.com/63504047/117304990-f647da00-ae9b-11eb-9d68-b538b4d984d6.png)

![Uploading image.png…]()

**Comment by pallupz** [comment]
Or use the latest code

**Comment by jiteshlalwani** [comment]
Yes after the latest pull, It is working fine. Thanks!
