### ISSUE TITLE
Booking Response Code: 409

### ISSUE THREAD

**Issue by aatish-kayyath** [pallupz/covid-vaccine-booking#96]
Centers available in BBMP from 06-05-2021 as of 2021-05-06 18:02:17: 155
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                           | district   |   pincode |   available | date       | slots                                                                        |
+=======+================================+============+===========+=============+============+==============================================================================+
|     1 | APOLLO HOSPITAL SHESHADRIPURAM | BBMP       |    560020 |           1 | 10-05-2021 | ['09:00AM-11:00AM', '11:00AM-01:00PM', '01:00PM-03:00PM', '03:00PM-05:30PM'] |
+-------+--------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
AUTO-BOOKING IS ENABLED. PROCEEDING WITH FIRST CENTRE, DATE, and SLOT.
============> Got Choice: Center #1, Slot #1
Booking with info: {'beneficiaries': ['773xxxxx153340'], 'dose': 1, 'center_id': 604866, 'session_id': '4779f94a-d50d-47bf-9601-765156018b40', 'slot': '09:00AM-11:00AM'}
================================= ATTEMPTING BOOKING ==================================================
Booking Response Code: 409
Booking Response : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}
Response: 409 : {"errorCode":"APPOIN0040","error":"This vaccination center is completely booked for the selected date."}

Is this happening to anyone else? FYI : yes-please was typed.

**Comment by pallupz** [comment]
It does happen from time to time when a session is shown as available and by the time its selected, it gets filled

**Comment by pallupz** [comment]
it shouldn't have stopped the loop though

**Comment by Sidbeheraunsw** [comment]
I think you should directly book slot 3 or 4 instead of slot 1 because people will have a tendency to select the first available option

**Comment by lets-get-vaccinated** [comment]
Anyone running the script at the time mentioned by Author should get the same prompt or there are chances of different responses because of 5 secs lag?

**Comment by pallupz** [comment]
@Sidbeheraunsw slot selection has been randomized. Will still use the first center and date though.
