### ISSUE TITLE
45+ booking problem

### ISSUE THREAD

**Issue by mah2001** [pallupz/covid-vaccine-booking#97]
hello i am trying to book  slot for relatives in 45+ slots but the script is not showing any 45+ slots. i choose a beneficiary with 45 plus age and still it shows me hospital with 18-44 age group. Can you please help me.

**Comment by pallupz** [comment]
That's weird. There is already filtering on the basis of age. Could you check simultaneously from script and from portal? See if the responses are matching?

**Comment by mah2001** [comment]
ok will keep it running today and lets see will let you know

**Comment by pallupz** [comment]
I will close this for now. If you do find something, please do share the screenshot or logs with PII removed.
